version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo HelloBro...
  build:
    commands:
      - echo Build started on `date`
      - yarn
      - yarn build
cache:
  paths:
    - './node_modules/**/*'